default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog
  username: postgres
  password: www123
  host: localhost

test:
  <<: *default
  database: blog_test
  username: postgres
  password: www123
  host: localhost

production:
  <<: *default
  database: blog_prod
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
